-- telescope.nvim
vim.api.nvim_set_keymap('n', '<leader>,', '<cmd>Telescope buffers<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>/', '<cmd>Telescope grep_string<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>:', '<cmd>Telescope command_history<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader><space>', '<cmd>Telescope find_files<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>fb', '<cmd>Telescope buffers<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>ff', '<cmd>Telescope find_files<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>fF', '<cmd>Telescope find_files cwd=<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>fr', '<cmd>Telescope oldfiles<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>fR', '<cmd>Telescope oldfiles cwd=<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>gc', '<cmd>Telescope git_commits<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>gs', '<cmd>Telescope git_status<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sa', '<cmd>Telescope autocommands<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sb', '<cmd>Telescope buffers<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sc', '<cmd>Telescope command_history<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sC', '<cmd>Telescope commands<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sd', '<cmd>Telescope lsp_document_diagnostics<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sD', '<cmd>Telescope lsp_workspace_diagnostics<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sg', '<cmd>Telescope grep_string<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sG', '<cmd>Telescope grep_string cwd=<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sh', '<cmd>Telescope help_tags<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sH', '<cmd>Telescope highlights<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sk', '<cmd>Telescope keymaps<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sM', '<cmd>Telescope man_pages<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sm', '<cmd>Telescope marks<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>so', '<cmd>Telescope options<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sR', '<cmd>Telescope resume<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sw', '<cmd>Telescope grep_string word=\\<\\><cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sW', '<cmd>Telescope grep_string word=\\<\\> cwd=<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>uC', '<cmd>Telescope colorscheme<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>ss', '<cmd>Telescope lsp_document_symbols<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>sS', '<cmd>Telescope lsp_workspace_symbols<cr>', { noremap = true, silent = true })