vim.api.nvim_set_keymap('n', '<leader>dB', '<cmd>lua require("dap").set_breakpoint(nil, nil, vim.fn.input("Breakpoint condition: "))<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>db', '<cmd>lua require("dap").toggle_breakpoint()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dc', '<cmd>lua require("dap").continue()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dC', '<cmd>lua require("dap").run_to_cursor()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dg', '<cmd>lua require("dap").repl.open()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>di', '<cmd>lua require("dap").step_into()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dj', '<cmd>lua require("dap").down()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dk', '<cmd>lua require("dap").up()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dl', '<cmd>lua require("dap").run_last()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>do', '<cmd>lua require("dap").step_out()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dO', '<cmd>lua require("dap").step_over()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dp', '<cmd>lua require("dap").pause()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dr', '<cmd>lua require("dapui").toggle()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>ds', '<cmd>lua require("dap").repl.run_last()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dt', '<cmd>lua require("dap").disconnect()<cr>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dw', '<cmd>lua require("dapui").widgets()<cr>', { noremap = true, silent = true })

vim.api.nvim_set_keymap('n', '<leader>td', '<cmd>lua require("lazyvim.plugins.extras.edtest.core").debug_nearest()<cr>', { noremap = true, silent = true })